### ISSUE TITLE
Adding to bookdown

### ISSUE THREAD

**Issue by csgillespie** [rstudio/bookdown#101]
Would you add https://github.com/csgillespie/efficientR to bookdown please.

----

I've created an account. When I try
```
> bookdown::publish_book(render = "local")
```

I get:
```
 Hide Traceback
 
 Rerun with Debug
 Error in rsconnect::deploySite(siteDir = getwd(), siteName = name, account = account,  : 
  index file with site entry not found in /data/ncsg3/github/efficientR 
3 stop("index file with site entry not found in ", siteDir) 
2 rsconnect::deploySite(siteDir = getwd(), siteName = name, account = account, 
    server = server, render = render) 
1 bookdown::publish_book(render = "local") 
```

I have an index.Rmd file in the base directory (https://raw.githubusercontent.com/csgillespie/efficientR/master/index.Rmd)

Thanks

**Comment by yihui** [comment]
The issue should be fixed by https://github.com/csgillespie/efficientR/pull/36

**Comment by csgillespie** [comment]
I've fixed (I think) the issues with the yml:

 * [_output.yml](https://github.com/csgillespie/efficientR/blob/master/_output.yml)
 * [_bookdown.yml](https://github.com/csgillespie/efficientR/blob/master/_bookdown.yml)
 * [index.Rmd.yml](https://github.com/csgillespie/efficientR/blob/master/index.Rmd) 


But I'm still getting (new) errors:
```
bookdown::publish_book(render = "local", account="csgillespie")
```
gives

```
Preparing to deploy site...
Update application currently deployed at
https://bookdown.org/csgillespie/efficientR/? [Y/n] Y
DONE
Uploading bundle for site: 46...DONE
Deploying bundle: 218 for site: 46 ...
Error: HTTP 400
POST https://bookdown.org/__api__/applications/46/deploy
You cannot change the type of application once deployed. Try deploying this as a new application instead of updating an existing one.
```

----

If I omit `account` from `publish_book` I get:
```
Error: Please specify the account name (there is more than one account registered on this system)
```

**Comment by jjallaire** [comment]
Maybe delete the existing published document from the rsconnect server then
try to re-publish?

**Comment by csgillespie** [comment]
@jjallaire Just tried deleting the app from the server) with various combinations of deleting the `rsconnect` directory). Still the same error.

**Comment by jjallaire** [comment]
Then I'm mystified. @CBarraford Could you take a look at why this deploy might be failing?

**Comment by trestletech** [comment]
Mea culpa. We have a fix for this building now and will have it out later this afternoon.

**Comment by ChaitaC** [comment]
Latest build with the fix is now on bookdown.org

**Comment by csgillespie** [comment]
Thanks, success (https://bookdown.org/csgillespie/efficientR/)
