### ISSUE TITLE
Adding a dash in theorem env messes up the output

### ISSUE THREAD

**Issue by cderv** [rstudio/bookdown#1233]
Again thank you so much for everything you did, regarding this and https://github.com/rstudio/bookdown/pull/940, really can't thank you enough.
Quick question though, if I may?
I expected the div syntax to allow me to make full use of `rmarkdown` format, as opposed to the more *limited* block engine?
Therefore, I was expecting this to work:
```
::: {.theorem}`
`r if (out_type=="beamer") "- "` Let $m$ be an even integer and $p$ be any integer. Then, $m \cdot p$ is an even integer.
:::
```
but funny enough, when i compile, the whole theorem gets gobbled up - nothing prints...
(I took this from my document, but if I add the same `` `r ` `` command into your sample bookdown book theorem in chapter 5, i get the exact same result, obviously.
Should i be expecting the `` `r ` `` command causes the theorem to no longer appear in the pdf?

Since the answer is probably no, I tried a much simpler version and I modified only your chapter 5 theorem, adding a simple `-`:
`- For a right triangle`, etc...
Doing so messes up the github compile (I get two messy bullet points) and in the `bookdown::pdf_book` compile, I no longer get the theorem at all.... (same for my custom `bookdown::beamer_presentation2`).
Seems very odd to meL since I am only adding one character, I can't be messing it up??
just to confirm the issue is not on my end, I tried directly with your bookdown template and i am getting the same result, so i am guessing you should be able to reproduce very easily and tell me if i am doing something wrong.

many thanks
thomas

_Originally posted by @tchevri in https://github.com/rstudio/bookdown/issues/1089#issuecomment-898957864_

**Comment by cderv** [comment]
Hi @tchevri, 

I think you found an issue. We use a Lua filter to power this feature, and I think we only expect a paragraph inside such env. Adding a `-` first will not create a paragrah but a bullet list element and our Lua filter does not seem to support that.

**Comment by tchevri** [comment]
Ok - I hope I am not spamming you, but following your help and advice with https://github.com/rstudio/bookdown/issues/1232, I decided to give this a shot:

    ::: {.block data-latex="{Notations}"}
    - Given any 2 vectors $x=(x_{1},\ldots,x_{n})$, and $y=(y_{1},\ldots,y_{n})$:  
    \begin{align}
    	x=		 &y,~~if~x_{i}=y_{i},~i=1,\ldots,n `r if (out_type=="beamer") "\\notag"`\\
    	x\geq  &y,~~if~x_{i}\geq y_{i},~i=1,\ldots,n `r if (out_type=="beamer") "\\notag"`\\
    	x>		 &y,~~if~x\geq y,~and~x\neq y `r if (out_type=="beamer") "\\notag"`\\
    	x\gg 	 &y,~~if~x_{i}>y_{i},~i=1,\ldots,n `r if (out_type=="beamer") "\\notag"`
    \end{align}
    :::

and I was expecting this to fail just as above. 
But it's working just fine - I am getting a nice Notations block.
I thought it might be helpful to let you know...
Sincere apologies if not (so must be numerating these blocks that's causing the problem, as you suggested?)
and guess what - i can't thank you (and the others too) enough for all the help with this most awesome package.
so again - many thanks,
thomas

**Comment by cderv** [comment]
Yes, this is directly using the Custom Block features: https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html based on Pandoc feature. This will create a `block` environment in LaTeX that you probably have defined in your preamble. 

````tex
\begin{block}{Notations}
...
\end{block}
````

We don't do any processing as we are doing with Theorems Env (the one listed in here: https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#theorems
For those, we are doing a bit of work instead of the user, like adding the necessary definition in the `.tex` file and or adding a label so that it can be referenced. We also make sure that the Theorems and Proofs env looks quite the same in HTML and PDF.

The syntax you used will work with all Rmd document, and not only with a **bookdown** format. But it will require that you define your own environment. 

Does it make sense ?

**Comment by cderv** [comment]
@tchevri this should be now fixed in the dev version of bookdown

```r
remotes::install_github("rstudio/bookdown")
```

**Comment by tchevri** [comment]
so sorry it took me so long to check, all the more since this is a feature I am really looking forward to using asap.
so I ran `remotes::install_github("rstudio/bookdown")` and I am on `building 'bookdown_0.23.2.tar.gz': `DONE (bookdown)`, i.e. 0.23.2 is installed.

I confirm that when I compile the demo book, your fix works perfectly for `bookdown::beamer_presentation2:`
Thank you so much for that - aawesome.

However, I am not experiencing the same luck in other formats.
Just to be super clear, I start from your demo example and I simply change your `05-blocks.Rmd` file (exactly as above).
Specifically, if I put `-` in front of `- For a right triangle` the output is now messed up. I get two bullet points and `\@ref(thm:tri)` gets converted to `??`.
Same for the `proof` environment below.
That's when I compile in GitHub format.

Can I add a couple of things I don't quite understand?
just below the `proof` in that file, I try to add:
::: {.block data-latex="{Remark}"}
For $n>1$, the vectors $x$ and $y$ need not be comparable under any of the categories above; e.g. $x=\left( 2,1\right)$ and $y=\left( 1,2\right)$.
:::
When I compile in github format `bookdown::gitbook:`, the text displays normally, but it's not an environment.
Did I miss something?
Am I supposed to do something else?
When I use it with `bookdown::beamer_presentation2:` it works perfect, as per your suggestion.

When I compile with `bookdown::pdf_book:`, I get:
```
! LaTeX Error: Environment block undefined.

Error: LaTeX failed to compile _main.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See _main.log for more info.
Execution halted
```
I am so sorry for not being more helpful - please, let me know what else I can do! And again thanks a ton for all the amazing help.

**Comment by cderv** [comment]
> However, I am not experiencing the same luck in other formats.
Just to be super clear, I start from your demo example and I simply change your 05-blocks.Rmd file (exactly as above).
Specifically, if I put - in front of - For a right triangle the output is now messed up. I get two bullet points and \@ref(thm:tri) gets converted to ??.
Same for the proof environment below.
That's when I compile in GitHub format.

What exactly are you trying to write, as output ? 
I tried what you described, and yes it seems to not work. However, having a theorem only composed of bullet point is not expected currently. Theorems are expected to start with a paragraph. Something like 
![image](https://user-images.githubusercontent.com/6791940/131338799-1b9f0fd5-ec44-4687-b61e-1b4b791e8b78.png)

````markdown
::: {.theorem #tri name="An interesting theorem"}
We are talking about

- For a right triangle, if $c$ denotes the *length* of the hypotenuse
and $a$ and $b$ denote the lengths of the **other** two sides, we have
$$a^2 + b^2 = c^2$$
:::
````

We can try support more styling but the primary aim of this feature in **bookdown** was to provide similar theorem in HTML than the one you can create with LaTeX and _amsmath_ theorem env (like [those](https://fr.overleaf.com/learn/latex/Theorems_and_proofs))

Currently what you are trying is this: 
```markdown
::: {.theorem #tri}
- For a right triangle, if $c$ denotes the *length* of the hypotenuse
and $a$ and $b$ denote the lengths of the **other** two sides, we have
$$a^2 + b^2 = c^2$$
:::
```

and output like this in PDF
![image](https://user-images.githubusercontent.com/6791940/131339172-9b1c4845-dc43-4695-a4c4-9e780beb9de5.png)

So is using bullet point as first paragraph in theorem something we should try support or not ? I am talking about time to fix/implement regarding usage in the wild. 

> I try to add:
::: {.block data-latex="{Remark}"}
For $n>1$, the vectors $x$ and $y$ need not be comparable under any of the categories above; e.g. $x=\left( 2,1\right)$ and $y=\left( 1,2\right)$.
:::

`.block` is not an environment defined in **bookdown**. You can use it with **beamer** because it is defined in the format: See [Overleaf tutorial](https://fr.overleaf.com/learn/latex/Beamer_Presentations:_A_Tutorial_for_Beginners_(Part_3)%E2%80%94Blocks,_Code,_Hyperlinks_and_Buttons#Blocks)
**rmarkdown** allow one to use custom block, outside of Bookdown, as explained in https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html but you would need to defined the environment in LaTeX to make it work. Same with HTML if the class `.block` means nothing in the theme you are using. 

From the cookbook
> It is up to the user to define the appearance of their <div> blocks via CSS for the HTML output. Similarly, for LaTeX output, you may use the command \newenvironment to define the environment if it has not been defined, or \renewenvironment to redefine an existing environment in LaTeX. In the LaTeX definitions, you can decide on the appearance of these blocks in PDF.

I let you reread this doc, and tell me if there is still something not clear or missing. 

Thank you !

**Comment by tchevri** [comment]
thank you for all these pointers - will review and revert if anything still not clear, but i understand your viewpoint - thank you so much for your time and help / support - much appreciated.
