### ISSUE TITLE
Site won't build when using hugo-academic theme

### ISSUE THREAD

**Issue by adisarid** [rstudio/bookdown#673]
I have followed the [recommended workflow](https://bookdown.org/yihui/blogdown/workflow.html) step-by-step. Opened up a new Rproject, then typed `blogdown::new_site(theme = "gcushen/hugo-academic")`.

The theme downloads but then I get this error:

```
Error: Unable to find theme Directory: C:\TEMP\adis_blog\themes\academic
```

From looking at the directory, I don't know why it's looking for the theme in this location, the theme is extracted to `themes\hugo-academic`. (with the additional `hugo-`. So something is looking in the wrong place...

I tried changing the directory name to academic, but that didn't work either, I guess something else breaks... dependencies someplace else?

I changed back the directory name to `hugo-academic` and  tried to bypass this with `blogdown::build_site()` and I get:

```
'C:\Users\Adi' is not recognized as an internal or external command,
operable program or batch file.
Error in shell(cmd, mustWork = TRUE, intern = intern) : 
  '"C:\Users\Adi Sarid\AppData\Roaming\Hugo\hugo.exe" -d "public" --themesDir themes -t hugo-academic' execution failed with error code 1
```

I understand that the shell get's stuck because there is a space character in the location for `hugo.exe`. I also tried running it myself from the folder using powershell, but it did not solve the issues.

Using RStudio 1.2.1237 on a windows 10 machine. Any pointers?
P.S., I did manage to install the default theme, but would like to do the blog with the academic theme.

```
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=Hebrew_Israel.1255  LC_CTYPE=Hebrew_Israel.1255    LC_MONETARY=Hebrew_Israel.1255
[4] LC_NUMERIC=C                   LC_TIME=Hebrew_Israel.1255    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       bookdown_0.9     packrat_0.5.0    digest_0.6.18    later_0.7.5      R6_2.3.0        
 [7] magrittr_1.5     evaluate_0.12    blogdown_0.10    stringi_1.2.4    rstudioapi_0.9.0 promises_1.0.1  
[13] rmarkdown_1.11   tools_3.5.2      stringr_1.3.1    httpuv_1.4.5.1   xfun_0.4         compiler_3.5.2  
[19] htmltools_0.3.6  knitr_1.21   
```

**Comment by yihui** [comment]
Duplicate of https://github.com/rstudio/blogdown/issues/359

**Comment by yihui** [comment]
I think you reported to the wrong repo. This is the bookdown repo instead of blogdown, but I have fixed the issue in blogdown anyway. You can install the development version via

```r
remotes::install_github('rstudio/blogdown')
```

Thanks!

**Comment by adisarid** [comment]
Wrong repo. Opps. I guess too many "down" packages got me mixed up :)
Anyways, thanks @yihui - I'll try the dev version!

**Comment by yihui** [comment]
No worries. Yes, too many "down" packages :)

**Comment by hcp4715** [comment]
Hi, Yihui,

Thanks for this great package.

I encountered a similar problem when running `serve_site()` today. It's a bit weird because everything worked about one month ago. 

I re-installed blogdown from github but the problem persists.

I am using win 10; R version 3.6.1 (2019-07-05); Rstudio version 1.2.1335; blogdown v0.15.1; hugo 0.58.2

![image](https://user-images.githubusercontent.com/7300419/65079841-465cea80-d9a0-11e9-9b5d-d03fbf98cd99.png)

Thanks in advance.

**Comment by sagitaninta** [comment]
I got also problem with `blogdown::serve_site()` after updating everything.

```
> blogdown::serve_site()
Building sites â€¦ Total in 1597 ms
Error: Error building site: "D:\Master\Rcourse\myWebsite\content\author\admin\_index.md:27:1": unmarshal failed: Near line 26 (last key parsed 'interests'): strings cannot contain newlines
Building sites â€¦ Total in 360 ms
Error: Error building site: "D:\Master\Rcourse\myWebsite\content\author\admin\_index.md:27:1": unmarshal failed: Near line 26 (last key parsed 'interests'): strings cannot contain newlines
The system cannot find the path specified.
Error in shell(cmd, mustWork = TRUE, intern = intern) : 
  '"C:\Users\sagit\AppData\Roaming\Hugo\hugo.exe" -b / -D -F -d "public" --themesDir themes -t academic' execution failed with error code 1
```

Win 10, R version 3.6.2; Rstudio Version 1.2.5019;  blogdown v0.17, hugo 0.61

**Comment by meersel** [comment]
Also got the similar problem with the "gcushen/hugo-academic theme".

See script and output below

> install_theme("gcushen/hugo-academic", theme_example = TRUE, update_config = TRUE)
trying URL 'https://github.com/gcushen/hugo-academic/archive/master.zip'
Content length 126 bytes
downloaded 5.3 MB

Error in utils::unzip(zipfile, exdir = tmpdir) : 
  cannot open file 'be305ddb1d3f/hugo-academic-master/exampleSite/resources/_gen/images/authors/admin/avatar_hu52a603635ecebd45650b162dadabb4e5_12861_270x270_fill_q90_lanczos_center.jpg': No such file or directory

**Comment by cderv** [comment]
Hi @meersel , 

this is the bookdown repository and not blogdown repos. You should look into issues there. 
I think yours is related to https://github.com/rstudio/blogdown/issues/433

Please, look for issues in the correct repository and open one in this correct repo if none exist yet. Thank you !
